name: Android CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: gradle

    - name: Grant Execute Permission for Gradle
      run: chmod +x gradlew

    # Humne yahan resource validation aur lint ko skip karne wale flags lagaye hain
    run: ./gradlew assembleDebug -Pandroid.experimental.disableResourcesValidation=true -x lint

    # ARTIFACTS BOX STEP
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Mimi-Launcher-APK
        path: "**/build/outputs/apk/debug/*.apk"
